version: '3.8'

services:
  app:
    build: .
    container_name: pingme_fastapi
    restart: always
    command: uvicorn app.main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/usr/src/app 
    ports:
      - "8000:8000"
    env_file:
      - .env 
    depends_on:
      - db
      - redis
    networks:
      - pingme_network

  db:
    image: postgres:15-alpine
    container_name: pingme_postgres
    restart: always
    env_file:
      - .env 
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - pingme_network

  redis:
    image: redis:7-alpine
    container_name: pingme_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - pingme_network

networks:
  pingme_network:
    driver: bridge

volumes:
  postgres_data:
