version: '3.9'

services:
  backend:
    build: .
    container_name: fastapi-backend
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: pingme_user
      POSTGRES_PASSWORD: pingme_pass
      POSTGRES_DB: chatapp
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
